<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Switch to cibuild0060655 for browser and cibuild0061023 everything else -->
    <AvaVersion>12.0.999-cibuild0061023-alpha</AvaVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Avalonia packages -->
    <!-- Important: keep version in sync! -->
    <PackageVersion Include="Avalonia" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Controls.ItemsRepeater" Version="11.2.999-cibuild0046261-alpha" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.iOS" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaVersion)" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="DynamicData" Version="9.4.1" />
    <PackageVersion Include="HotAvalonia" Version="3.0.1" />
    <PackageVersion Include="HotAvalonia.Core" Version="3.0.1" />
    <PackageVersion Include="Jab" Version="0.12.0" />
    <PackageVersion Include="LibVLCSharp.Avalonia" Version="3.9.5" />
    <PackageVersion Include="LiveMarkdown.Avalonia" Version="1.4.0" />
    <PackageVersion Include="Markdig" Version="0.44.0" />
    <PackageVersion Include="Material.Icons.Avalonia" Version="3.0.0-preview3.1" />
    <PackageVersion Include="ShadUI" Version="0.1.5" />
    <PackageVersion Include="Svg.Controls.Avalonia" Version="11.3.6.2" />
    <PackageVersion Include="TextMateSharp.Grammars" Version="1.0.70" />
    <PackageVersion Include="VideoLAN.LibVLC.Android" Version="3.7.0-beta" />
    <PackageVersion Include="VideoLAN.LibVLC.Mac" Version="3.1.3.1" />
    <PackageVersion Include="VideoLAN.LibVLC.UWP" Version="3.3.2" />
    <PackageVersion Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
    <PackageVersion Include="WebView.Avalonia" Version="11.0.0.1" />
    <PackageVersion Include="WebView.Avalonia.Desktop" Version="11.0.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.17" />
    <PackageVersion Include="Xaml.Behaviors.Avalonia" Version="11.3.9" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="11.3.999-cibuild0055466-alpha" />
  </ItemGroup>
</Project>