<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<PublishAot>false</PublishAot>
	<NuGetAuditMode>direct</NuGetAuditMode>
	<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
 
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DynamicData" />
    <PackageReference Include="Jab" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="WebView.Avalonia" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avalonia.Controls.DataGrid\Avalonia.Controls.DataGrid.csproj" />
    <ProjectReference Include="..\ext\LunarChatSharp\LunarChatSharp\LunarChatSharp.csproj" />
    <ProjectReference Include="..\LiveMarkdown.Avalonia\LiveMarkdown.Avalonia.csproj" />
    <ProjectReference Include="..\ShadUI\ShadUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Account\FriendRequestIListtem.axaml.cs">
      <DependentUpon>FriendRequestIListtem.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Channels\ChannelItem.axaml.cs">
      <DependentUpon>ChannelItem.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\ReportServerDialog.axaml.cs">
      <DependentUpon>ReportServerDialog.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\User\Settings\Developer\DeveloperList.axaml.cs">
      <DependentUpon>DeveloperList.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\Styles\Markdown.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
</Project>
