<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-android36.0</TargetFramework>
		<SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ApplicationId>com.FluxpointDev.LunarChat</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>

		<AndroidEnableMultiDex>True</AndroidEnableMultiDex>
		<!--<HotAvaloniaRemote>true</HotAvaloniaRemote>-->
	</PropertyGroup>


	<ItemGroup>
		<AndroidResource Include="Icon.png">
			<Link>Resources\drawable\Icon.png</Link>
		</AndroidResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Android" />
		<PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
		<!--<PackageReference Include="HotAvalonia">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>-->
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LunarChatApp\LunarChatApp.csproj" />
	</ItemGroup>
</Project>
